[workspace]
members = [
    "src/alex_backend",
    "src/icp_swap",
    "src/registry",
    "src/tokenomics",
    "src/logs",
    "src/xrc",
    "src/user",
    "src/logs",
    "src/lbry_fun"

]
resolver = "2"
