/**
 * Report generator for validation results
 */
class ReportGenerator {
  /**
   * Generate markdown report
   * @param {Object} validationResults - Results from EpochValidator
   * @param {Object} metadata - Pool metadata
   * @returns {string} Markdown formatted report
   */
  generateMarkdownReport(validationResults, metadata) {
    let report = '';

    // Header
    report += '# Comprehensive Tokenomics Validation Report\n\n';
    report += `**Pool ID:** ${metadata.poolId}\n`;
    report += `**Validation Time:** ${metadata.timestamp}\n`;
    report += `**Overall Status:** ${validationResults.passed ? '✅ PASSED' : '❌ FAILED'}\n\n`;

    // Executive Summary
    report += '## Executive Summary\n\n';
    const passCount = Object.values(validationResults).filter(v => v && v.passed).length - 1; // -1 for 'passed' field
    const totalCount = Object.keys(validationResults).length - 1; // -1 for 'passed' field
    report += `**Tests Passed:** ${passCount}/${totalCount}\n\n`;

    report += '| Validation | Status |\n';
    report += '|-----------|--------|\n';
    report += `| Cumulative Accuracy | ${validationResults.cumulativeAccuracy.passed ? '✅ Pass' : '❌ Fail'} |\n`;
    report += `| Thresholds Array | ${validationResults.thresholdsArray.passed ? '✅ Pass' : '❌ Fail'} |\n`;
    report += `| Rewards Array | ${validationResults.rewardsArray.passed ? '✅ Pass' : '❌ Fail'} |\n`;
    report += `| Halving Progression | ${validationResults.halvingProgression.passed ? '✅ Pass' : '❌ Fail'} |\n`;
    report += `| Current State | ${validationResults.currentState.passed ? '✅ Pass' : '❌ Fail'} |\n\n`;

    // Detailed sections
    report += this._formatCumulativeSection(validationResults.cumulativeAccuracy);
    report += this._formatThresholdsSection(validationResults.thresholdsArray);
    report += this._formatRewardsSection(validationResults.rewardsArray);
    report += this._formatHalvingSection(validationResults.halvingProgression, metadata.tokenConfig);
    report += this._formatCurrentStateSection(validationResults.currentState);

    // Recommendations
    report += '## Recommendations\n\n';
    if (validationResults.passed) {
      report += '✅ All validations passed. The tokenomics implementation is working correctly.\n\n';
      report += '**Next Steps:**\n';
      report += '- Continue monitoring with periodic validations\n';
      report += '- Archive this report for historical reference\n';
    } else {
      report += '❌ Issues detected. Recommended actions:\n\n';

      if (!validationResults.cumulativeAccuracy.passed) {
        report += '- **Cumulative Accuracy Failure**: Investigate discrepancy between actual and projected supply\n';
      }
      if (!validationResults.thresholdsArray.passed) {
        report += '- **Thresholds Mismatch**: Verify token creation parameters match projection\n';
      }
      if (!validationResults.rewardsArray.passed) {
        report += '- **Rewards Mismatch**: Check reward calculation logic in tokenomics canister\n';
      }
      if (!validationResults.halvingProgression.passed) {
        report += '- **Halving Violations**: Review halving step implementation in canister\n';
      }
      if (!validationResults.currentState.passed) {
        report += '- **State Inconsistency**: Refresh insights data and verify canister state\n';
      }
    }

    report += '\n---\n\n';
    report += `*Generated by tokenomics_validator.js*\n`;

    return report;
  }

  /**
   * Generate console report
   * @param {Object} validationResults - Results from EpochValidator
   */
  generateConsoleReport(validationResults) {
    console.log('\n╔════════════════════════════════════════════════════════════════╗');
    console.log('║      COMPREHENSIVE TOKENOMICS VALIDATION RESULTS              ║');
    console.log('╚════════════════════════════════════════════════════════════════╝\n');

    this._printSection('1. Cumulative Supply Accuracy', validationResults.cumulativeAccuracy);
    this._printSection('2. Thresholds Array Validation', validationResults.thresholdsArray);
    this._printSection('3. Rewards Array Validation', validationResults.rewardsArray);
    this._printSection('4. Halving Mechanics Validation', validationResults.halvingProgression);
    this._printSection('5. Current State Consistency', validationResults.currentState);

    console.log('\n' + '─'.repeat(66) + '\n');
    if (validationResults.passed) {
      console.log('✅ Overall Status: PASSED\n');
      console.log('All validations completed successfully.\n');
    } else {
      console.log('❌ Overall Status: FAILED\n');
      console.log('One or more validations failed. See report for details.\n');
    }
  }

  _printSection(title, data) {
    const status = data.passed ? '✅ PASS' : '❌ FAIL';
    console.log(`\n${title}: ${status}`);
    console.log('─'.repeat(66));
  }

  _formatCumulativeSection(data) {
    let section = '## 1. Cumulative Supply Accuracy\n\n';
    section += `**Status:** ${data.passed ? '✅ Pass' : '❌ Fail'}\n\n`;

    section += '| Metric | Value |\n';
    section += '|--------|-------|\n';
    section += `| Total Secondary Burned | ${this._formatNumber(data.totalSecondaryBurned)} E8S |\n`;
    section += `| Actual Primary Supply | ${this._formatNumber(data.actual)} E8S |\n`;
    section += `| Expected Primary Supply | ${this._formatNumber(data.expected)} E8S |\n`;
    section += `| Variance | ${data.variance.toFixed(4)}% |\n`;
    section += `| Pass Criteria | < 5% variance |\n\n`;

    if (data.passed) {
      section += '✅ The actual primary supply matches the projected supply within acceptable variance.\n\n';
    } else {
      section += '❌ The actual primary supply deviates significantly from projection.\n\n';
    }

    return section;
  }

  _formatThresholdsSection(data) {
    let section = '## 2. Thresholds Array Validation\n\n';
    section += `**Status:** ${data.passed ? '✅ Pass' : '❌ Fail'}\n\n`;

    section += '| Metric | Value |\n';
    section += '|--------|-------|\n';
    section += `| Actual Threshold Count | ${data.actualCount} |\n`;
    section += `| Expected Threshold Count | ${data.expectedCount} |\n`;
    section += `| Mismatches | ${data.mismatches.length} |\n\n`;

    if (data.mismatches.length > 0) {
      section += '**Mismatches Found:**\n\n';
      section += '| Index | Actual | Expected |\n';
      section += '|-------|--------|----------|\n';
      data.mismatches.forEach(m => {
        section += `| ${m.index} | ${m.actual || 'null'} | ${m.expected || 'null'} |\n`;
      });
      section += '\n';
    } else {
      section += '✅ All thresholds match the projection exactly.\n\n';
    }

    return section;
  }

  _formatRewardsSection(data) {
    let section = '## 3. Rewards Array Validation\n\n';
    section += `**Status:** ${data.passed ? '✅ Pass' : '❌ Fail'}\n\n`;

    section += '| Metric | Value |\n';
    section += '|--------|-------|\n';
    section += `| Actual Reward Count | ${data.actualCount} |\n`;
    section += `| Expected Reward Count | ${data.expectedCount} |\n`;
    section += `| Tolerance | ±${data.tolerance} units (4-decimal format) |\n`;
    section += `| Mismatches | ${data.mismatches.length} |\n\n`;

    if (data.mismatches.length > 0) {
      section += '**Mismatches Found:**\n\n';
      section += '| Index | Actual | Expected | Difference |\n';
      section += '|-------|--------|----------|------------|\n`;
      data.mismatches.slice(0, 10).forEach(m => {
        section += `| ${m.index} | ${m.actual || 'null'} | ${m.expected || 'null'} | ${m.difference || 'N/A'} |\n`;
      });
      if (data.mismatches.length > 10) {
        section += `\n*...and ${data.mismatches.length - 10} more mismatches*\n`;
      }
      section += '\n';
    } else {
      section += '✅ All rewards match the projection within tolerance.\n\n';
    }

    section += '*Note: Rewards are stored in 4-decimal format (1.0 token = 10,000 units)*\n\n';

    return section;
  }

  _formatHalvingSection(data, config) {
    let section = '## 4. Halving Mechanics Validation\n\n';
    section += `**Status:** ${data.passed ? '✅ Pass' : '❌ Fail'}\n\n`;

    section += '| Metric | Value |\n';
    section += '|--------|-------|\n';
    section += `| Total Epochs | ${data.totalEpochs} |\n`;
    section += `| Expected Ratio | ${(data.expectedRatio * 100).toFixed(1)}% (${config.halving_step}% halving step) |\n`;
    section += `| Tolerance | ±${(data.tolerance * 100).toFixed(1)}% |\n`;
    section += `| Violations | ${data.violations.length} |\n\n`;

    if (data.violations.length > 0) {
      section += '**Violations Found:**\n\n';
      section += '| From Epoch | To Epoch | Previous Reward | Current Reward | Actual Ratio | Expected Ratio | Variance |\n';
      section += '|------------|----------|-----------------|----------------|--------------|----------------|----------|\n';
      data.violations.forEach(v => {
        section += `| ${v.fromEpoch} | ${v.toEpoch} | ${v.previousReward} | ${v.currentReward} | ${(v.actualRatio * 100).toFixed(2)}% | ${(v.expectedRatio * 100).toFixed(2)}% | ${(v.variance * 100).toFixed(2)}% |\n`;
      });
      section += '\n';
    } else {
      section += `✅ All epoch transitions follow the ${config.halving_step}% halving step correctly.\n\n`;
    }

    return section;
  }

  _formatCurrentStateSection(data) {
    let section = '## 5. Current State Consistency\n\n';
    section += `**Status:** ${data.passed ? '✅ Pass' : '❌ Fail'}\n\n`;

    section += '| Metric | Value |\n';
    section += '|--------|-------|\n';
    section += `| Current Threshold Index | ${data.currentIndex} |\n`;
    section += `| Total Burned (Canister) | ${this._formatNumber(data.totalBurned)} E8S |\n`;
    section += `| Total Burned (Insights) | ${this._formatNumber(data.insightsBurned)} E8S |\n`;
    section += `| Burned Amounts Match | ${data.burnedMatch ? '✅ Yes' : '❌ No'} |\n`;
    section += `| Index Correct | ${data.indexCorrect ? '✅ Yes' : '❌ No'} |\n`;
    section += `| Threshold Count | ${data.thresholdCount} |\n\n`;

    section += `**Index Validation:** ${data.indexReason}\n\n`;

    if (!data.burnedMatch) {
      section += '⚠️ **Warning:** Canister and insights report different burn amounts. Insights data may be stale.\n\n';
    }

    return section;
  }

  _formatNumber(num) {
    return num.toLocaleString('en-US');
  }
}

module.exports = ReportGenerator;
