import React from "react";
import { ChevronUp } from "lucide-react";
function PinaxSkeleton() {
    return (React.createElement("div", { className: "py-10 px-4 sm:px-6 md:px-10 flex-grow flex justify-center" },
        React.createElement("div", { className: "max-w-2xl w-full flex flex-col justify-center items-center gap-8" },
            React.createElement("div", { className: "flex flex-col justify-center items-center" },
                React.createElement("div", { className: "h-8 w-24 bg-gray-300 dark:bg-gray-700 animate-pulse rounded-md mb-2" }),
                React.createElement("div", { className: "h-4 w-64 bg-gray-300 dark:bg-gray-700 animate-pulse rounded-md" })),
            React.createElement("div", { className: "flex justify-center items-center gap-4" },
                React.createElement("div", { className: "h-10 w-32 bg-gray-300 dark:bg-gray-700 animate-pulse rounded-full" }),
                React.createElement("div", { className: "h-10 w-32 bg-gray-300 dark:bg-gray-700 animate-pulse rounded-full" })),
            React.createElement("div", { className: "w-full flex justify-center items-center gap-6" },
                React.createElement("div", { className: "flex justify-center items-center gap-2" },
                    React.createElement("div", { className: "w-5 h-5 bg-gray-300 dark:bg-gray-700 animate-pulse rounded-full" }),
                    React.createElement("div", { className: "w-16 h-4 bg-gray-300 dark:bg-gray-700 animate-pulse rounded-md" })),
                React.createElement("div", { className: "flex-grow h-0.5 bg-gray-300 dark:bg-gray-700 animate-pulse" }),
                React.createElement("div", { className: "flex justify-center items-center gap-2" },
                    React.createElement("div", { className: "w-5 h-5 bg-gray-300 dark:bg-gray-700 animate-pulse rounded-full" }),
                    React.createElement("div", { className: "w-16 h-4 bg-gray-300 dark:bg-gray-700 animate-pulse rounded-md" })),
                React.createElement("div", { className: "flex-grow h-0.5 bg-gray-300 dark:bg-gray-700 animate-pulse" }),
                React.createElement("div", { className: "flex justify-center items-center gap-2" },
                    React.createElement("div", { className: "w-5 h-5 bg-gray-300 dark:bg-gray-700 animate-pulse rounded-full" }),
                    React.createElement("div", { className: "w-16 h-4 bg-gray-300 dark:bg-gray-700 animate-pulse rounded-md" }))),
            React.createElement("div", { className: "w-full font-roboto-condensed space-y-1" },
                React.createElement("button", { className: "w-full font-syne text-xl flex items-center justify-between group" },
                    React.createElement("div", { className: "h-7 w-56 bg-gray-300 dark:bg-gray-700 animate-pulse rounded-md" }),
                    React.createElement("span", { className: "text-sm text-gray-300 dark:text-gray-600" },
                        React.createElement(ChevronUp, { className: "w-6 h-6 text-gray-300 dark:text-gray-600", strokeWidth: 2 }))),
                React.createElement("div", { className: "relative border-2 rounded-lg py-8 px-4 sm:px-6 md:px-8 text-center border-gray-300 dark:border-gray-700 border-dashed" },
                    React.createElement("div", { className: "space-y-6" },
                        React.createElement("div", { className: "flex justify-center" },
                            React.createElement("div", { className: "h-5 w-48 bg-gray-200 dark:bg-gray-800 animate-pulse rounded-md" })),
                        React.createElement("div", { className: "flex justify-center" },
                            React.createElement("div", { className: "h-5 w-8 bg-gray-200 dark:bg-gray-800 animate-pulse rounded-md" })),
                        React.createElement("div", { className: "flex justify-center" },
                            React.createElement("div", { className: "h-10 w-28 bg-gray-200 dark:bg-gray-800 animate-pulse rounded-full" })),
                        React.createElement("div", { className: "grid grid-cols-1 xs:grid-cols-2 md:grid-cols-4 gap-4 max-w-2xl mx-auto" }, [1, 2, 3, 4].map((index) => (React.createElement("div", { key: index, className: "flex flex-col items-start justify-center gap-2 p-3 bg-white/50 dark:bg-gray-800/50 border rounded dark:border-gray-700" },
                            React.createElement("div", { className: "h-5 w-20 bg-gray-200 dark:bg-gray-800 animate-pulse rounded-md" }),
                            React.createElement("div", { className: "w-full flex flex-col items-center justify-center gap-2 p-2 bg-card/50 border border-border rounded dark:border-gray-700" },
                                React.createElement("div", { className: "h-10 w-10 bg-gray-200 dark:bg-gray-800 animate-pulse rounded-md" }),
                                React.createElement("div", { className: "h-4 w-20 bg-gray-200 dark:bg-gray-800 animate-pulse rounded-md" }))))))))))));
}
export default PinaxSkeleton;
