// Export all swap pages for easy importing
export { default as BalancePage } from './BalancePage';
export { default as SwapPage } from './SwapPage';
export { default as BurnPage } from './BurnPage';
export { default as StakePage } from './StakePage';
export { default as SendPage } from './SendPage';
export { default as ReceivePage } from './ReceivePage';
export { default as HistoryPage } from './HistoryPage';
export { default as InsightsPage } from './InsightsPage';
export { default as RedeemPage } from './RedeemPage';